### ISSUE TITLE
Accuracy_reimplementation

### ISSUE THREAD

**Issue by xifang001** [JunMa11/SegLoss#28]
Hi, @JunMa11,

I tried reimplementing the liver segmentation using dice loss. Everything goes well though, the performance is a little lower than the results in your paper. I use the SoftDiceloss and the LiTS dataset. I conducted the experiments, using the same splits as provided. When I evaluate the liver segmentation, I combine the liver and liver tumor into one channel. The average Dice result is 94.51.

Do you have any idea about that or suggestions?
Best,
Xi

**Comment by JunMa11** [comment]
Hi @xifang001 ,

It seems that your network segments both liver and liver tumors, right?
In my experiments, I combine the liver and liver tumor (e.g., gt = np.uint8(gt>0) ) as a single mask. It is normal that the results have a slight fluctuation because the default training is non-deterministic. 

BTW, liver segmentation is almost a solved problem in LITS dataset. I would recommend paying more attention to the there three tasks. I also released the dataset with baidu net disk.
https://github.com/JunMa11/SegLoss/tree/master/test

Best,
Jun
